@startuml
digraph G {
0 -> 5 [label = 9]
1 -> 7 [label = 57]
1 -> 2 [label = 46]
2 -> 6 [label = 5]
3 -> 1 [label = 89]
4 -> 8 [label = 47]
5 -> 8 [label = 39]
6 -> 5 [label = 33]
6 -> 4 [label = 23]
6 -> 3 [label = 78]
7 -> 0 [label = 88]
7 -> 9 [label = 17]
8 -> 1 [label = 75]
9 -> 5 [label = 81]
}
@enduml
